<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Author extends User
{
    protected $table ="users";
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('author', function (Builder $builder){
           $builder->whereHas('posts');
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id');
    }

    public function tags()
    {
        return $this->morphToMany(Tag::class,'taggable');
    }


    public function images()
    {
        return $this->morphToMany(Tag::class,'taggable');
    }

}
