<?php

namespace App;

use App\Scopes\AuthorScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Author extends User
{
    protected $table ="users";
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new AuthorScope);
    }

    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id');
    }

    public function tags()
    {
        return $this->morphToMany(Tag::class,'taggable')->withTimestamps();
    }


    public function images()
    {
        return $this->morphToMany(Image::class,'imageable')->withTimestamps();
    }

}
